# alias ci-compose="docker-compose -f docker-compose.yml -f ci-compose.yml"

volumes:
  app_node_modules:
  app_vendor:

services:
  tests:
    image: vovimayhem/php-demo:testing
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USER: ${USER:-developer}
    volumes:
      - .:/var/www/html
      - app_node_modules:/var/www/html/node_modules
      - app_vendor:/var/www/html/vendor
    entrypoint: /var/www/html/bin/dev-entrypoint
    command: php artisan test
    depends_on:
      - mysql
      - redis
    environment:
      APP_NAME: Demo
      APP_ENV: local
      APP_KEY: ${APP_KEY:-base64:vZqr5Aje1wUQf2LaixbR33XC+t2asy4iaf844QfO+Uc=}
      APP_DEBUG: "${APP_DEBUG:-true}"
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-debug}

      APP_URL: ${APP_URL:-http://localhost}

      LOG_CHANNEL: stack
      LOG_LEVEL: debug

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: demo_development
      DB_USERNAME: demo
      DB_PASSWORD: 3x4mpl3P455w0rd

      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: "null"
      MAIL_FROM_NAME: Demo

